<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2 ' . $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('css/style.css')) ?>


    <!-- assetics start-->
    <?php
    echo $this->plugin('HeadLink');
    echo $this->plugin('HeadStyle');
    echo $this->plugin('HeadScript');
    ?>
    <!-- assetics end-->

</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img
                    src="<?php echo $this->basePath('img/zf2-logo.png') ?>"
                    alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Skeleton Application') ?></a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a>
                </li>
            </ul>
        </div>
        <!--/.nav-collapse -->
    </div>
</nav>
<div class="container appContent">
    <?php echo $this->content; ?>
    <?php echo $this->workflowContent; ?>
    <hr>
    <footer>
        <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies
            Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
    </footer>
</div>
<!-- /container -->
<?php echo $this->inlineScript() ?>


<script type="text/javascript">
//
//    (function ($) {
//
//        var Renderer = function (canvas) {
//            var canvas = $(canvas).get(0);
//            var ctx = canvas.getContext("2d");
//            var particleSystem;
//
//            var that = {
//                init: function (system) {
//                    //начальная инициализация
//                    particleSystem = system;
//                    particleSystem.screenSize(canvas.width, canvas.height);
//                    particleSystem.screenPadding(80);
//                    that.initMouseHandling();
//                },
//
//                redraw: function () {
//                    //действия при перересовке
//                    ctx.fillStyle = "white"; //белым цветом
//                    ctx.fillRect(0, 0, canvas.width, canvas.height); //закрашиваем всю область
//
//                    particleSystem.eachEdge( //отрисуем каждую грань
//                        function (edge, pt1, pt2) { //будем работать с гранями и точками её начала и конца
//                            ctx.strokeStyle = "rgba(0,0,0, .333)"; //грани будут чёрным цветом с некой прозрачностью
//                            ctx.lineWidth = 1; //толщиной в один пиксель
//                            ctx.beginPath();  //начинаем рисовать
//                            ctx.moveTo(pt1.x, pt1.y); //от точки один
//                            ctx.lineTo(pt2.x, pt2.y); //до точки два
//                            ctx.stroke();
//                        });
//
//                    particleSystem.eachNode( //теперь каждую вершину
//                        function (node, pt) {  //получаем вершину и точку где она
//                            var w = 10;   //ширина квадрата
//                            ctx.fillStyle = "orange"; //с его цветом понятно
//                            ctx.fillRect(pt.x - w / 2, pt.y - w / 2, w, w); //рисуем
//                            ctx.fillStyle = "black"; //цвет для шрифта
//                            ctx.font = 'italic 13px sans-serif'; //шрифт
//                            ctx.fillText(node.name, pt.x + 8, pt.y + 8); //пишем имя у каждой точки
//                        });
//                },
//
//                initMouseHandling: function () { //события с мышью
//                    var dragged = null;   //вершина которую перемещают
//                    var handler = {
//                        clicked: function (e) { //нажали
//                            var pos = $(canvas).offset(); //получаем позицию canvas
//                            _mouseP = arbor.Point(e.pageX - pos.left, e.pageY - pos.top); //и позицию нажатия кнопки относительно canvas
//                            dragged = particleSystem.nearest(_mouseP); //определяем ближайшую вершину к нажатию
//                            if (dragged && dragged.node !== null) {
//                                dragged.node.fixed = true; //фиксируем её
//                            }
//                            $(canvas).bind('mousemove', handler.dragged); //слушаем события перемещения мыши
//                            $(window).bind('mouseup', handler.dropped);  //и отпускания кнопки
//                            return false;
//                        },
//                        dragged: function (e) { //перетаскиваем вершину
//                            var pos = $(canvas).offset();
//                            var s = arbor.Point(e.pageX - pos.left, e.pageY - pos.top);
//
//                            if (dragged && dragged.node !== null) {
//                                var p = particleSystem.fromScreen(s);
//                                dragged.node.p = p; //тянем вершину за нажатой мышью
//                            }
//
//                            return false;
//                        },
//                        dropped: function (e) { //отпустили
//                            if (dragged === null || dragged.node === undefined) return; //если не перемещали, то уходим
//                            if (dragged.node !== null) dragged.node.fixed = false; //если перемещали - отпускаем
//                            dragged = null; //очищаем
//                            $(canvas).unbind('mousemove', handler.dragged); //перестаём слушать события
//                            $(window).unbind('mouseup', handler.dropped);
//                            _mouseP = null;
//                            return false;
//                        }
//                    }
//                    // слушаем события нажатия мыши
//                    $(canvas).mousedown(handler.clicked);
//                },
//
//            }
//            return that;
//        }
//
//        $(document).ready(function () {
//            sys = arbor.ParticleSystem(50); // создаём систему
//            sys.parameters({gravity: true}); // гравитация вкл
//            sys.renderer = Renderer("#viewport") //начинаем рисовать в выбраной области
//
////            $.getJSON("http://test-workflow.local:9080/assets/workflow/designer/js/libs/arbor/data.json", //получаем с сервера файл с данными
////
////
////
////
//////                function (data) {
//////                    $.each(data.nodes, function (i, node) {
//////
//////                        sys.addNode(node.name); //добавляем вершину
//////
//////                        console.log(2222);
//////                        if (i > 0) {
//////                            return false;
//////                        }
//////                    });
//////
////////                            $.each(data.edges, function(i,edge){
////////                                sys.addEdge(sys.getNode(edge.src),sys.getNode(edge.dest)); //добавляем грань
////////                            });
//////                }
////            )
//
//
//
//
//            sys.addNode('test1');
//            sys.addNode('test2');
//            sys.addNode('test3');
//            sys.addNode('test4');
//            sys.addNode('test5');
//            sys.addNode('test6');
//            sys.addNode('test7');
//            sys.addNode('test8');
//            sys.addNode('test9');
//
//
//
//
//
//
//
//        })
//
//    })(this.jQuery)

</script>


</body>
</html>
